#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FlashCardsPort.Droid.Resource", IsApplication=true)]

namespace FlashCardsPort.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layout_constraintBaseline_creator = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int layout_constraintBaseline_toBaselineOf = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int layout_constraintBottom_creator = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int layout_constraintBottom_toBottomOf = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int layout_constraintBottom_toTopOf = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int layout_constraintDimensionRatio = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int layout_constraintEnd_toEndOf = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int layout_constraintEnd_toStartOf = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_constraintGuide_begin = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_constraintGuide_end = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintGuide_percent = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintHorizontal_bias = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintHorizontal_chainPacked = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintHorizontal_weight = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintLeft_creator = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintLeft_toLeftOf = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintLeft_toRightOf = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintRight_creator = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintRight_toLeftOf = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintRight_toRightOf = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintStart_toEndOf = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintStart_toStartOf = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintTop_creator = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintTop_toBottomOf = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintTop_toTopOf = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintVertical_bias = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintVertical_chainPacked = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintVertical_weight = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_editor_absoluteX = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_editor_absoluteY = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_goneMarginBottom = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_goneMarginEnd = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_goneMarginLeft = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_goneMarginRight = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_goneMarginStart = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_goneMarginTop = 2130772003;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cross = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_sourth = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Picture = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int tick = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int Camera = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int Card_1 = 2131099649;
			
			// aapt resource value: 0x7f06000f
			public const int Cost_deck = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int Deck = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int Galery = 2131099653;
			
			// aapt resource value: 0x7f060021
			public const int activity_dash_board = 2131099681;
			
			// aapt resource value: 0x7f060012
			public const int activity_forgot_pass = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int activity_main = 2131099672;
			
			// aapt resource value: 0x7f060026
			public const int activity_sign_up = 2131099686;
			
			// aapt resource value: 0x7f060002
			public const int card_icon = 2131099650;
			
			// aapt resource value: 0x7f060023
			public const int dashboard_btn_edit = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int dashboard_btn_exam = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int dashboard_btn_exit = 2131099685;
			
			// aapt resource value: 0x7f060022
			public const int dashboard_welcome = 2131099682;
			
			// aapt resource value: 0x7f060011
			public const int delete_item = 2131099665;
			
			// aapt resource value: 0x7f060030
			public const int done = 2131099696;
			
			// aapt resource value: 0x7f060010
			public const int edit_item = 2131099664;
			
			// aapt resource value: 0x7f060017
			public const int forgot_btn_back = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int forgot_btn_reset = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int forgot_email = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int forgot_message = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int icon = 2131099667;
			
			// aapt resource value: 0x7f060003
			public const int icon_card = 2131099651;
			
			// aapt resource value: 0x7f06002f
			public const int item1 = 2131099695;
			
			// aapt resource value: 0x7f06000b
			public const int list = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int list_card = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int list_cards = 2131099656;
			
			// aapt resource value: 0x7f06001e
			public const int login_btn_forgot_password = 2131099678;
			
			// aapt resource value: 0x7f06001d
			public const int login_btn_login = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int login_btn_signup = 2131099680;
			
			// aapt resource value: 0x7f06001a
			public const int login_email = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int login_input_email = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int login_input_password = 2131099675;
			
			// aapt resource value: 0x7f06001f
			public const int login_layout_or = 2131099679;
			
			// aapt resource value: 0x7f06001c
			public const int login_password = 2131099676;
			
			// aapt resource value: 0x7f060000
			public const int parent = 2131099648;
			
			// aapt resource value: 0x7f06002c
			public const int signup_btn_forgot_password = 2131099692;
			
			// aapt resource value: 0x7f06002e
			public const int signup_btn_login = 2131099694;
			
			// aapt resource value: 0x7f06002b
			public const int signup_btn_register = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int signup_email = 2131099688;
			
			// aapt resource value: 0x7f060027
			public const int signup_input_email = 2131099687;
			
			// aapt resource value: 0x7f060029
			public const int signup_input_password = 2131099689;
			
			// aapt resource value: 0x7f06002d
			public const int signup_layout_or = 2131099693;
			
			// aapt resource value: 0x7f06002a
			public const int signup_password = 2131099690;
			
			// aapt resource value: 0x7f06000e
			public const int title_deck = 2131099662;
			
			// aapt resource value: 0x7f06000a
			public const int translate = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int translate_card = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int word = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int word_card = 2131099654;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int add_card_admin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int cards_deck = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Custom_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int decks = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int dialog_add_cards_admin = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int dialog_add_deck_admin = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int edit_delete_item = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int forgot_password = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int main_menu_admin = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int sign_up = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int deck_admin_actionbar = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int main = 2131034113;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[]
			{
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003};
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 1;
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 2;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 3;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 4;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainPacked = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainPacked = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 36;
			
			public static int[] ConstraintSet = new int[]
			{
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843701,
					16843702,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003};
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_layout_marginEnd = 10;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 9
			public const int ConstraintSet_android_layout_marginStart = 9;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 11
			public const int ConstraintSet_layout_constraintBaseline_creator = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_layout_constraintBottom_creator = 13;
			
			// aapt resource value: 14
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 15;
			
			// aapt resource value: 16
			public const int ConstraintSet_layout_constraintDimensionRatio = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 17;
			
			// aapt resource value: 18
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 18;
			
			// aapt resource value: 19
			public const int ConstraintSet_layout_constraintGuide_begin = 19;
			
			// aapt resource value: 20
			public const int ConstraintSet_layout_constraintGuide_end = 20;
			
			// aapt resource value: 21
			public const int ConstraintSet_layout_constraintGuide_percent = 21;
			
			// aapt resource value: 22
			public const int ConstraintSet_layout_constraintHorizontal_bias = 22;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constraintHorizontal_chainPacked = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constraintHorizontal_weight = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintLeft_creator = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintRight_creator = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintRight_toRightOf = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintStart_toEndOf = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintStart_toStartOf = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintTop_creator = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintTop_toTopOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintVertical_bias = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintVertical_chainPacked = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintVertical_weight = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_editor_absoluteX = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_editor_absoluteY = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_goneMarginBottom = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_goneMarginEnd = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_goneMarginLeft = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_goneMarginRight = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_goneMarginStart = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_goneMarginTop = 46;
			
			public static int[] LinearConstraintLayout = new int[]
			{
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
